version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  trip:
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - full
    container_name: trip
    restart: always
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres