version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - "5732:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
  trip:
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - full
    container_name: trip
    restart: always
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis