spring:
  application:
    name: trip-backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

