spring:
  profiles:
    active: dev
  application:
    name: trip-backend
  config:
    import: optional:file:.env.local[.properties]
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5732/postgres}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  override-with-generic-response: false

jwt:
  secret: ${JWT_SECRET:secret}
  access-token:
    ttl: 1000000
