spring:
  profiles:
    active: dev
  application:
    name: trip-backend
  config:
    import: optional:file:.env.local[.properties]
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5732/postgres}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: ./migrations/master.xml
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  redis:
    host: redis
    port: 6379

logging:
  level:
    root: debug

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  override-with-generic-response: false

jwt:
  secret: ${JWT_SECRET:secret}
  access-token:
    ttl: 1000000

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include[0]: health
        include[1]: info
        include[2]: metrics
        include[3]: prometheus
  appoptics:
    metrics:
      export:
        enabled: true

#otel:
#  exporter:
#    otlp:
#      endpoint: http://localhost:4317
#  resource:
#    attributes:
#      service.name: your-service-name
